run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - gosec         # Security issues
    - copyloopvar   # Check for pointers to loop variables (replaces exportloopref)
    - gocritic      # The most opinionated linter
    - bodyclose     # Check HTTP response body is closed
    - contextcheck  # Check context is passed correctly
    - errorlint     # Check error wrapping
    - nilerr        # Check that nil errors are not returned

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocritic:
    disabled-checks:
      - exitAfterDefer  # Allow os.Exit in main after defer for proper cleanup

  gofmt:
    simplify: true

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G304  # File path provided as taint input - acceptable for our use case

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic

